### ISSUE TITLE
CSS structure

### ISSUE THREAD

**Issue by jenseneducation-sharon-tan** [jenseneducation-fredrik-blomberglarsson/airbean#22]
Be consistent in using id and classes . 
Use the same type of casing (normally kebab-casing) in naming all your classes and id.
Avoid repeating styles (eg. font-family, color) . Refactoring of styles.

**Comment by jenseneducation-Clara-Berglund** [comment]
Good point, we will look at our names but won't have time to change and re-arrange the whole project.
